import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
import { Headers } from "./components/Header";

import { KakeiboProvider } from "./context/KakeiboContext";
import { BrowserRouter, Routes, Route } from "react-router-dom";

function App() {
  return (
    <KakeiboProvider>
      <BrowserRouter>
        <Routes>
          <Route path="/" element={<Kakeibos />} />
          <Route path="/detail/:id" element={<KakeiboDetail />} />
        </Routes>
      </BrowserRouter>
    </KakeiboProvider>
  );
}

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <>
            <Headers />
            {children}
          </>
        </Providers>
      </body>
    </html>
  );
}
